import { AppLocale } from '@/i18n/routing';
export type ExperienceOverride = Record<AppLocale, { shortDescription: string; longDescription: string }>;
export const experienceOverrides: Record<string, ExperienceOverride> = {
  'azure-pearl-24m': {
    tr: { shortDescription: 'Bodrum çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Azure Pearl 24M, Bodrum kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Bodrum with a gentler, more polished pace at sea.', longDescription: 'Azure Pearl 24M frames the coastline of Bodrum through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Bodrum بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Azure Pearl 24M سواحل Bodrum من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'golden-tide-28m': {
    tr: { shortDescription: 'Göcek çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Golden Tide 28M, Göcek kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Göcek with a gentler, more polished pace at sea.', longDescription: 'Golden Tide 28M frames the coastline of Göcek through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Göcek بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Golden Tide 28M سواحل Göcek من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'royal-horizon-31m': {
    tr: { shortDescription: 'Yalıkavak çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Royal Horizon 31M, Yalıkavak kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Yalıkavak with a gentler, more polished pace at sea.', longDescription: 'Royal Horizon 31M frames the coastline of Yalıkavak through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Yalıkavak بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Royal Horizon 31M سواحل Yalıkavak من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'bosphorus-signature-cruise': {
    tr: { shortDescription: 'İstanbul çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Bosphorus Signature Cruise, İstanbul kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from İstanbul with a gentler, more polished pace at sea.', longDescription: 'Bosphorus Signature Cruise frames the coastline of İstanbul through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من İstanbul بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Bosphorus Signature Cruise سواحل İstanbul من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'moonwake-26m': {
    tr: { shortDescription: 'Marmaris çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Moonwake 26M, Marmaris kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Marmaris with a gentler, more polished pace at sea.', longDescription: 'Moonwake 26M frames the coastline of Marmaris through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Marmaris بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Moonwake 26M سواحل Marmaris من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'celeste-mare-32m': {
    tr: { shortDescription: 'Göcek çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Celeste Mare 32M, Göcek kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Göcek with a gentler, more polished pace at sea.', longDescription: 'Celeste Mare 32M frames the coastline of Göcek through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Göcek بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Celeste Mare 32M سواحل Göcek من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'aegean-reverie-27m': {
    tr: { shortDescription: 'Fethiye çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Aegean Reverie 27M, Fethiye kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Fethiye with a gentler, more polished pace at sea.', longDescription: 'Aegean Reverie 27M frames the coastline of Fethiye through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Fethiye بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Aegean Reverie 27M سواحل Fethiye من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'marina-noir-29m': {
    tr: { shortDescription: 'Yalıkavak çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Marina Noir 29M, Yalıkavak kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Yalıkavak with a gentler, more polished pace at sea.', longDescription: 'Marina Noir 29M frames the coastline of Yalıkavak through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Yalıkavak بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Marina Noir 29M سواحل Yalıkavak من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'dolce-riva-25m': {
    tr: { shortDescription: 'Bodrum çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Dolce Riva 25M, Bodrum kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from Bodrum with a gentler, more polished pace at sea.', longDescription: 'Dolce Riva 25M frames the coastline of Bodrum through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من Bodrum بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Dolce Riva 25M سواحل Bodrum من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'serenity-deck-30m': {
    tr: { shortDescription: 'İstanbul çıkışlı, günü sakin bir tempoyla denize taşıyan zarif özel charter.', longDescription: 'Serenity Deck 30M, İstanbul kıyılarında özel boarding, incelikli servis akışı ve özenle seçilmiş duraklarla ilerleyen daha rafine bir charter günü sunar. Gün, acele hissi yerine ritmi doğru ayarlanmış bir deniz deneyimi olarak tasarlanır.' },
    en: { shortDescription: 'A composed private charter setting out from İstanbul with a gentler, more polished pace at sea.', longDescription: 'Serenity Deck 30M frames the coastline of İstanbul through private boarding, discreet service and a route selected with more intention than noise. The day is designed to feel measured, polished and visually memorable from the first departure moment to the final return.' },
    ar: { shortDescription: 'رحلة يخت خاصة تنطلق من İstanbul بإيقاع أهدأ وحضور أكثر أناقة على البحر.', longDescription: 'يقدّم Serenity Deck 30M سواحل İstanbul من خلال صعود خاص وخدمة هادئة ومسار مختار بعناية أكبر من الضجيج المعتاد. تم تصميم اليوم ليبدو متزناً وأنيقاً ولافتاً بصرياً منذ لحظة الانطلاق وحتى العودة الأخيرة.' },
  },
  'club-flipper-yalikavak': {
    tr: { shortDescription: 'Yalıkavak için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'CLUB FLIPPER Yalıkavak, Yalıkavak konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Yalıkavak, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'CLUB FLIPPER Yalıkavak approaches a stay in Yalıkavak as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Yalıkavak يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل CLUB FLIPPER Yalıkavak مع الإقامة في Yalıkavak بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'ege-signature-escape': {
    tr: { shortDescription: 'Bodrum için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Ege Signature Escape, Bodrum konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Bodrum, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Ege Signature Escape approaches a stay in Bodrum as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Bodrum يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Ege Signature Escape مع الإقامة في Bodrum بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'coastal-grand-retreat': {
    tr: { shortDescription: 'Göcek için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Coastal Grand Retreat, Göcek konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Göcek, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Coastal Grand Retreat approaches a stay in Göcek as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Göcek يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Coastal Grand Retreat مع الإقامة في Göcek بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'old-city-grand-suite': {
    tr: { shortDescription: 'İstanbul için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Old City Grand Suite, İstanbul konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in İstanbul, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Old City Grand Suite approaches a stay in İstanbul as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في İstanbul يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Old City Grand Suite مع الإقامة في İstanbul بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'bosphorus-terrace-residence': {
    tr: { shortDescription: 'İstanbul için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Bosphorus Terrace Residence, İstanbul konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in İstanbul, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Bosphorus Terrace Residence approaches a stay in İstanbul as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في İstanbul يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Bosphorus Terrace Residence مع الإقامة في İstanbul بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'cappadocia-stone-mansion': {
    tr: { shortDescription: 'Kapadokya için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Cappadocia Stone Mansion, Kapadokya konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Kapadokya, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Cappadocia Stone Mansion approaches a stay in Kapadokya as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Kapadokya يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Cappadocia Stone Mansion مع الإقامة في Kapadokya بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'bodrum-marina-loft': {
    tr: { shortDescription: 'Bodrum için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Bodrum Marina Loft, Bodrum konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Bodrum, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Bodrum Marina Loft approaches a stay in Bodrum as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Bodrum يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Bodrum Marina Loft مع الإقامة في Bodrum بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'gocek-bay-residence': {
    tr: { shortDescription: 'Göcek için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Göcek Bay Residence, Göcek konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Göcek, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Göcek Bay Residence approaches a stay in Göcek as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Göcek يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Göcek Bay Residence مع الإقامة في Göcek بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'alacati-courtyard-suite': {
    tr: { shortDescription: 'Alaçatı için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Alaçatı Courtyard Suite, Alaçatı konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Alaçatı, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Alaçatı Courtyard Suite approaches a stay in Alaçatı as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Alaçatı يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Alaçatı Courtyard Suite مع الإقامة في Alaçatı بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'antalya-riviera-penthouse': {
    tr: { shortDescription: 'Antalya için seçilmiş, dingin ritmi ve özenli servis hissiyle öne çıkan konaklama adresi.', longDescription: 'Antalya Riviera Penthouse, Antalya konaklamasını yalnızca bir oda teslimi olarak değil; varış anından itibaren daha sakin, daha seçili ve daha özenli bir deneyim olarak ele alır. Mekânın atmosferi, lokasyon avantajı ve servis dili birlikte düşünülerek konforun görünür olduğu bir konaklama kurgusu sunulur.' },
    en: { shortDescription: 'A selected address in Antalya, shaped around quiet comfort, considered service and a more composed stay.', longDescription: 'Antalya Riviera Penthouse approaches a stay in Antalya as more than a room key and check-in. Atmosphere, location advantage and service tone are considered together to create a quieter, more refined base for the rest of the journey.' },
    ar: { shortDescription: 'عنوان إقامة مختار في Antalya يجمع بين الراحة الهادئة والخدمة المتقنة وإيقاع إقامة أكثر رصانة.', longDescription: 'يتعامل Antalya Riviera Penthouse مع الإقامة في Antalya بوصفها أكثر من مجرد غرفة ومفتاح دخول. فالأجواء والموقع ونبرة الخدمة تُنسّق معاً لتكوين قاعدة إقامة أكثر هدوءاً ورقياً لبقية الرحلة.' },
  },
  'kapadokya-sunrise-classic': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Kapadokya Sunrise Classic, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Kapadokya Sunrise Classic places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Kapadokya Sunrise Classic الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'kapadokya-gold-flight': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Kapadokya Gold Flight, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Kapadokya Gold Flight places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Kapadokya Gold Flight الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'fairy-valley-private-flight': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Fairy Valley Private Flight, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Fairy Valley Private Flight places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Fairy Valley Private Flight الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'sunrise-photo-chase': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Sunrise Photo Chase, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Sunrise Photo Chase places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Sunrise Photo Chase الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'deluxe-dawn-balloon': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Deluxe Dawn Balloon, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Deluxe Dawn Balloon places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Deluxe Dawn Balloon الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'red-valley-signature': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Red Valley Signature, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Red Valley Signature places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Red Valley Signature الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'family-comfort-balloon': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Family Comfort Balloon, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Family Comfort Balloon places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Family Comfort Balloon الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'proposal-balloon-flight': {
    tr: { shortDescription: 'Kapadokya semalarında günün ilk ışıklarını daha sessiz ve ayrıcalıklı bir perspektiften izleten uçuş.', longDescription: 'Proposal Balloon Flight, Kapadokya semalarında gün doğumunun görsel etkisini daha kontrollü, daha konforlu ve daha zarif bir uçuş kurgusuyla sunar. Karşılama, kalkış hazırlığı ve iniş sonrası akış tek bir bütünlük içinde planlanır.' },
    en: { shortDescription: 'A sunrise flight over Kapadokya designed for softer pacing, wider views and a more elevated sense of occasion.', longDescription: 'Proposal Balloon Flight places the visual drama of Kapadokya into a sunrise flight format with calmer pacing and a more polished guest flow. Pickup, launch preparation and the post-flight rhythm are handled as one coherent experience.' },
    ar: { shortDescription: 'رحلة شروق فوق Kapadokya صيغت بإيقاع أهدأ وإطلالات أوسع وحضور أكثر تميزاً.', longDescription: 'يضع Proposal Balloon Flight الأثر البصري لمشاهد Kapadokya في صيغة طيران عند الشروق بإيقاع أكثر هدوءاً ومسار ضيافة أكثر أناقة. يتم التعامل مع الاستقبال والاستعداد للإقلاع وما بعد الهبوط كتجربة واحدة متماسكة.' },
  },
  'seaside-private-villa': {
    tr: { shortDescription: 'Bodrum için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Seaside Private Villa, Bodrum için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Bodrum balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Seaside Private Villa is a selected villa experience in Bodrum where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Bodrum توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Seaside Private Villa تجربة فيلا مختارة في Bodrum تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'mediterranean-cliff-villa': {
    tr: { shortDescription: 'Kaş için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Mediterranean Cliff Villa, Kaş için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Kaş balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Mediterranean Cliff Villa is a selected villa experience in Kaş where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Kaş توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Mediterranean Cliff Villa تجربة فيلا مختارة في Kaş تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'yalikavak-panorama-estate': {
    tr: { shortDescription: 'Yalıkavak için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Yalıkavak Panorama Estate, Yalıkavak için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Yalıkavak balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Yalıkavak Panorama Estate is a selected villa experience in Yalıkavak where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Yalıkavak توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Yalıkavak Panorama Estate تجربة فيلا مختارة في Yalıkavak تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'gocek-pine-retreat': {
    tr: { shortDescription: 'Göcek için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Göcek Pine Retreat, Göcek için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Göcek balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Göcek Pine Retreat is a selected villa experience in Göcek where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Göcek توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Göcek Pine Retreat تجربة فيلا مختارة في Göcek تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'kas-horizon-house': {
    tr: { shortDescription: 'Kaş için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Kaş Horizon House, Kaş için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Kaş balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Kaş Horizon House is a selected villa experience in Kaş where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Kaş توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Kaş Horizon House تجربة فيلا مختارة في Kaş تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'alacati-garden-villa': {
    tr: { shortDescription: 'Alaçatı için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Alaçatı Garden Villa, Alaçatı için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Alaçatı balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Alaçatı Garden Villa is a selected villa experience in Alaçatı where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Alaçatı توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Alaçatı Garden Villa تجربة فيلا مختارة في Alaçatı تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'fethiye-cove-residence': {
    tr: { shortDescription: 'Fethiye için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Fethiye Cove Residence, Fethiye için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Fethiye balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Fethiye Cove Residence is a selected villa experience in Fethiye where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Fethiye توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Fethiye Cove Residence تجربة فيلا مختارة في Fethiye تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'bodrum-platinum-villa': {
    tr: { shortDescription: 'Bodrum için mahremiyet, manzara ve kontrollü konforu aynı çerçevede buluşturan özel villa.', longDescription: 'Bodrum Platinum Villa, Bodrum için manzara, mahremiyet ve konfor dengesini aynı sahnede buluşturan seçili bir villa deneyimidir. Kalış süreci, yalnızca konaklama değil; daha sakin bir tempo, daha kişisel bir alan ve daha rafine bir günlük akış hissi yaratacak biçimde ele alınır.' },
    en: { shortDescription: 'A private villa in Bodrum balancing privacy, horizon views and an unhurried sense of comfort.', longDescription: 'Bodrum Platinum Villa is a selected villa experience in Bodrum where privacy, outlook and comfort remain in balance. Rather than feeling purely transactional, the stay is framed as a slower, more personal and more elegant way to inhabit the destination.' },
    ar: { shortDescription: 'فيلا خاصة في Bodrum توازن بين الخصوصية والمشهد وإحساس راقٍ بالراحة.', longDescription: 'Bodrum Platinum Villa تجربة فيلا مختارة في Bodrum تحافظ على توازن واضح بين الخصوصية والمشهد والراحة. ولا تُقدَّم الإقامة هنا كخيار عملي فقط، بل كطريقة أهدأ وأكثر شخصية وأناقة لعيش الوجهة.' },
  },
  'vip-transfer-and-karsilama': {
    tr: { shortDescription: 'İstanbul hattında kusursuz karşılama, şoförlü konfor ve ölçülü tempo sunan VIP transfer akışı.', longDescription: 'VIP Transfer & Karşılama, İstanbul hattında karşılama, bagaj koordinasyonu ve şoförlü sürüş konforunu aynı disiplin içinde bir araya getirir. Yolculuk boyunca öne çıkan unsur hız değil; pürüzsüz geçiş, görünür profesyonellik ve ölçülü bir hizmet ritmidir.' },
    en: { shortDescription: 'A chauffeur-driven transfer line in İstanbul built around polished arrivals, calm pacing and visible professionalism.', longDescription: 'VIP Transfer & Karşılama brings arrival handling, luggage coordination and chauffeured comfort together across İstanbul. The emphasis is not simply movement, but smoother transitions, visible care and a travel rhythm that stays composed from start to finish.' },
    ar: { shortDescription: 'مسار نقل فاخر في İstanbul يقوم على استقبال أنيق وإيقاع هادئ واحترافية ظاهرة.', longDescription: 'يجمع VIP Transfer & Karşılama بين الاستقبال وتنسيق الأمتعة وراحة السيارة مع السائق ضمن İstanbul. التركيز هنا ليس على الانتقال فحسب، بل على نعومة العبور والعناية الظاهرة وإيقاع سفر يبقى متزناً من البداية حتى النهاية.' },
  },
  'executive-airport-arrival': {
    tr: { shortDescription: 'İstanbul Airport hattında kusursuz karşılama, şoförlü konfor ve ölçülü tempo sunan VIP transfer akışı.', longDescription: 'Executive Airport Arrival, İstanbul Airport hattında karşılama, bagaj koordinasyonu ve şoförlü sürüş konforunu aynı disiplin içinde bir araya getirir. Yolculuk boyunca öne çıkan unsur hız değil; pürüzsüz geçiş, görünür profesyonellik ve ölçülü bir hizmet ritmidir.' },
    en: { shortDescription: 'A chauffeur-driven transfer line in İstanbul Airport built around polished arrivals, calm pacing and visible professionalism.', longDescription: 'Executive Airport Arrival brings arrival handling, luggage coordination and chauffeured comfort together across İstanbul Airport. The emphasis is not simply movement, but smoother transitions, visible care and a travel rhythm that stays composed from start to finish.' },
    ar: { shortDescription: 'مسار نقل فاخر في İstanbul Airport يقوم على استقبال أنيق وإيقاع هادئ واحترافية ظاهرة.', longDescription: 'يجمع Executive Airport Arrival بين الاستقبال وتنسيق الأمتعة وراحة السيارة مع السائق ضمن İstanbul Airport. التركيز هنا ليس على الانتقال فحسب، بل على نعومة العبور والعناية الظاهرة وإيقاع سفر يبقى متزناً من البداية حتى النهاية.' },
  },
  'bodrum-chauffeur-day': {
    tr: { shortDescription: 'Bodrum hattında kusursuz karşılama, şoförlü konfor ve ölçülü tempo sunan VIP transfer akışı.', longDescription: 'Bodrum Chauffeur Day, Bodrum hattında karşılama, bagaj koordinasyonu ve şoförlü sürüş konforunu aynı disiplin içinde bir araya getirir. Yolculuk boyunca öne çıkan unsur hız değil; pürüzsüz geçiş, görünür profesyonellik ve ölçülü bir hizmet ritmidir.' },
    en: { shortDescription: 'A chauffeur-driven transfer line in Bodrum built around polished arrivals, calm pacing and visible professionalism.', longDescription: 'Bodrum Chauffeur Day brings arrival handling, luggage coordination and chauffeured comfort together across Bodrum. The emphasis is not simply movement, but smoother transitions, visible care and a travel rhythm that stays composed from start to finish.' },
    ar: { shortDescription: 'مسار نقل فاخر في Bodrum يقوم على استقبال أنيق وإيقاع هادئ واحترافية ظاهرة.', longDescription: 'يجمع Bodrum Chauffeur Day بين الاستقبال وتنسيق الأمتعة وراحة السيارة مع السائق ضمن Bodrum. التركيز هنا ليس على الانتقال فحسب، بل على نعومة العبور والعناية الظاهرة وإيقاع سفر يبقى متزناً من البداية حتى النهاية.' },
  },
  'i-stanbul-executive-drive': {
    tr: { shortDescription: 'İstanbul hattında kusursuz karşılama, şoförlü konfor ve ölçülü tempo sunan VIP transfer akışı.', longDescription: 'İstanbul Executive Drive, İstanbul hattında karşılama, bagaj koordinasyonu ve şoförlü sürüş konforunu aynı disiplin içinde bir araya getirir. Yolculuk boyunca öne çıkan unsur hız değil; pürüzsüz geçiş, görünür profesyonellik ve ölçülü bir hizmet ritmidir.' },
    en: { shortDescription: 'A chauffeur-driven transfer line in İstanbul built around polished arrivals, calm pacing and visible professionalism.', longDescription: 'İstanbul Executive Drive brings arrival handling, luggage coordination and chauffeured comfort together across İstanbul. The emphasis is not simply movement, but smoother transitions, visible care and a travel rhythm that stays composed from start to finish.' },
    ar: { shortDescription: 'مسار نقل فاخر في İstanbul يقوم على استقبال أنيق وإيقاع هادئ واحترافية ظاهرة.', longDescription: 'يجمع İstanbul Executive Drive بين الاستقبال وتنسيق الأمتعة وراحة السيارة مع السائق ضمن İstanbul. التركيز هنا ليس على الانتقال فحسب، بل على نعومة العبور والعناية الظاهرة وإيقاع سفر يبقى متزناً من البداية حتى النهاية.' },
  },
  'marina-transfer-suite': {
    tr: { shortDescription: 'Yalıkavak hattında kusursuz karşılama, şoförlü konfor ve ölçülü tempo sunan VIP transfer akışı.', longDescription: 'Marina Transfer Suite, Yalıkavak hattında karşılama, bagaj koordinasyonu ve şoförlü sürüş konforunu aynı disiplin içinde bir araya getirir. Yolculuk boyunca öne çıkan unsur hız değil; pürüzsüz geçiş, görünür profesyonellik ve ölçülü bir hizmet ritmidir.' },
    en: { shortDescription: 'A chauffeur-driven transfer line in Yalıkavak built around polished arrivals, calm pacing and visible professionalism.', longDescription: 'Marina Transfer Suite brings arrival handling, luggage coordination and chauffeured comfort together across Yalıkavak. The emphasis is not simply movement, but smoother transitions, visible care and a travel rhythm that stays composed from start to finish.' },
    ar: { shortDescription: 'مسار نقل فاخر في Yalıkavak يقوم على استقبال أنيق وإيقاع هادئ واحترافية ظاهرة.', longDescription: 'يجمع Marina Transfer Suite بين الاستقبال وتنسيق الأمتعة وراحة السيارة مع السائق ضمن Yalıkavak. التركيز هنا ليس على الانتقال فحسب، بل على نعومة العبور والعناية الظاهرة وإيقاع سفر يبقى متزناً من البداية حتى النهاية.' },
  },
  'cappadocia-private-driver': {
    tr: { shortDescription: 'Kapadokya hattında kusursuz karşılama, şoförlü konfor ve ölçülü tempo sunan VIP transfer akışı.', longDescription: 'Cappadocia Private Driver, Kapadokya hattında karşılama, bagaj koordinasyonu ve şoförlü sürüş konforunu aynı disiplin içinde bir araya getirir. Yolculuk boyunca öne çıkan unsur hız değil; pürüzsüz geçiş, görünür profesyonellik ve ölçülü bir hizmet ritmidir.' },
    en: { shortDescription: 'A chauffeur-driven transfer line in Kapadokya built around polished arrivals, calm pacing and visible professionalism.', longDescription: 'Cappadocia Private Driver brings arrival handling, luggage coordination and chauffeured comfort together across Kapadokya. The emphasis is not simply movement, but smoother transitions, visible care and a travel rhythm that stays composed from start to finish.' },
    ar: { shortDescription: 'مسار نقل فاخر في Kapadokya يقوم على استقبال أنيق وإيقاع هادئ واحترافية ظاهرة.', longDescription: 'يجمع Cappadocia Private Driver بين الاستقبال وتنسيق الأمتعة وراحة السيارة مع السائق ضمن Kapadokya. التركيز هنا ليس على الانتقال فحسب، بل على نعومة العبور والعناية الظاهرة وإيقاع سفر يبقى متزناً من البداية حتى النهاية.' },
  },
  'private-gastronomy-route': {
    tr: { shortDescription: 'İstanbul için tadım, masa ritmi ve seçili adresleri rafine bir akşam kurgusunda buluşturan rota.', longDescription: 'Private Gastronomy Route, İstanbul içinde seçili masaları, güçlü mutfak adreslerini ve akşamın ritmini daha rafine bir gastronomi kurgusunda bir araya getirir. Rota, yalnızca rezervasyon listesi değil; atmosfer, servis dili ve masadaki genel his gözetilerek hazırlanır.' },
    en: { shortDescription: 'A dining route in İstanbul bringing selected tables and a refined evening rhythm into one curated line.', longDescription: 'Private Gastronomy Route draws together selected tables, stronger culinary addresses and a more polished evening sequence in İstanbul. The route is shaped around atmosphere, service quality and the overall feeling at the table, not just the reservation itself.' },
    ar: { shortDescription: 'مسار تذوق في İstanbul يجمع بين الطاولات المختارة وإيقاع أمسيات أكثر أناقة.', longDescription: 'يجمع Private Gastronomy Route بين الطاولات المختارة والعناوين الأجدر بالزيارة وإيقاع أمسية أكثر صقلاً في İstanbul. ويتم تشكيل المسار وفق الأجواء وجودة الخدمة والإحساس العام على المائدة، لا وفق الحجز وحده.' },
  },
  'bosphorus-supper-trail': {
    tr: { shortDescription: 'İstanbul için tadım, masa ritmi ve seçili adresleri rafine bir akşam kurgusunda buluşturan rota.', longDescription: 'Bosphorus Supper Trail, İstanbul içinde seçili masaları, güçlü mutfak adreslerini ve akşamın ritmini daha rafine bir gastronomi kurgusunda bir araya getirir. Rota, yalnızca rezervasyon listesi değil; atmosfer, servis dili ve masadaki genel his gözetilerek hazırlanır.' },
    en: { shortDescription: 'A dining route in İstanbul bringing selected tables and a refined evening rhythm into one curated line.', longDescription: 'Bosphorus Supper Trail draws together selected tables, stronger culinary addresses and a more polished evening sequence in İstanbul. The route is shaped around atmosphere, service quality and the overall feeling at the table, not just the reservation itself.' },
    ar: { shortDescription: 'مسار تذوق في İstanbul يجمع بين الطاولات المختارة وإيقاع أمسيات أكثر أناقة.', longDescription: 'يجمع Bosphorus Supper Trail بين الطاولات المختارة والعناوين الأجدر بالزيارة وإيقاع أمسية أكثر صقلاً في İstanbul. ويتم تشكيل المسار وفق الأجواء وجودة الخدمة والإحساس العام على المائدة، لا وفق الحجز وحده.' },
  },
  'bodrum-chefs-table-route': {
    tr: { shortDescription: 'Bodrum için tadım, masa ritmi ve seçili adresleri rafine bir akşam kurgusunda buluşturan rota.', longDescription: 'Bodrum Chef\'s Table Route, Bodrum içinde seçili masaları, güçlü mutfak adreslerini ve akşamın ritmini daha rafine bir gastronomi kurgusunda bir araya getirir. Rota, yalnızca rezervasyon listesi değil; atmosfer, servis dili ve masadaki genel his gözetilerek hazırlanır.' },
    en: { shortDescription: 'A dining route in Bodrum bringing selected tables and a refined evening rhythm into one curated line.', longDescription: 'Bodrum Chef\'s Table Route draws together selected tables, stronger culinary addresses and a more polished evening sequence in Bodrum. The route is shaped around atmosphere, service quality and the overall feeling at the table, not just the reservation itself.' },
    ar: { shortDescription: 'مسار تذوق في Bodrum يجمع بين الطاولات المختارة وإيقاع أمسيات أكثر أناقة.', longDescription: 'يجمع Bodrum Chef\'s Table Route بين الطاولات المختارة والعناوين الأجدر بالزيارة وإيقاع أمسية أكثر صقلاً في Bodrum. ويتم تشكيل المسار وفق الأجواء وجودة الخدمة والإحساس العام على المائدة، لا وفق الحجز وحده.' },
  },
  'cappadocia-cellar-journey': {
    tr: { shortDescription: 'Kapadokya için tadım, masa ritmi ve seçili adresleri rafine bir akşam kurgusunda buluşturan rota.', longDescription: 'Cappadocia Cellar Journey, Kapadokya içinde seçili masaları, güçlü mutfak adreslerini ve akşamın ritmini daha rafine bir gastronomi kurgusunda bir araya getirir. Rota, yalnızca rezervasyon listesi değil; atmosfer, servis dili ve masadaki genel his gözetilerek hazırlanır.' },
    en: { shortDescription: 'A dining route in Kapadokya bringing selected tables and a refined evening rhythm into one curated line.', longDescription: 'Cappadocia Cellar Journey draws together selected tables, stronger culinary addresses and a more polished evening sequence in Kapadokya. The route is shaped around atmosphere, service quality and the overall feeling at the table, not just the reservation itself.' },
    ar: { shortDescription: 'مسار تذوق في Kapadokya يجمع بين الطاولات المختارة وإيقاع أمسيات أكثر أناقة.', longDescription: 'يجمع Cappadocia Cellar Journey بين الطاولات المختارة والعناوين الأجدر بالزيارة وإيقاع أمسية أكثر صقلاً في Kapadokya. ويتم تشكيل المسار وفق الأجواء وجودة الخدمة والإحساس العام على المائدة، لا وفق الحجز وحده.' },
  },
  'ege-harvest-and-table': {
    tr: { shortDescription: 'Urla için tadım, masa ritmi ve seçili adresleri rafine bir akşam kurgusunda buluşturan rota.', longDescription: 'Ege Harvest & Table, Urla içinde seçili masaları, güçlü mutfak adreslerini ve akşamın ritmini daha rafine bir gastronomi kurgusunda bir araya getirir. Rota, yalnızca rezervasyon listesi değil; atmosfer, servis dili ve masadaki genel his gözetilerek hazırlanır.' },
    en: { shortDescription: 'A dining route in Urla bringing selected tables and a refined evening rhythm into one curated line.', longDescription: 'Ege Harvest & Table draws together selected tables, stronger culinary addresses and a more polished evening sequence in Urla. The route is shaped around atmosphere, service quality and the overall feeling at the table, not just the reservation itself.' },
    ar: { shortDescription: 'مسار تذوق في Urla يجمع بين الطاولات المختارة وإيقاع أمسيات أكثر أناقة.', longDescription: 'يجمع Ege Harvest & Table بين الطاولات المختارة والعناوين الأجدر بالزيارة وإيقاع أمسية أكثر صقلاً في Urla. ويتم تشكيل المسار وفق الأجواء وجودة الخدمة والإحساس العام على المائدة، لا وفق الحجز وحده.' },
  },
  'private-celebration-design': {
    tr: { shortDescription: 'Türkiye odağında, detayları sizin ritminize göre şekillenen özel planlama deneyimi.', longDescription: 'Private Celebration Design, Türkiye odağında şekillenen kutlama, aile seyahati ya da kurumsal planlama ihtiyaçlarını tek bir zarif çatı altında toplar. Süreç, programın her aşamasında kontrollü iletişim, görünür operasyon ve ölçülü bir teslim standardıyla ilerler.' },
    en: { shortDescription: 'A bespoke planning format shaped around Türkiye, refined to your pace, priorities and style of travel.', longDescription: 'Private Celebration Design gathers celebration, family travel or corporate planning needs around Türkiye into one controlled and elegant framework. The process remains visible, discreet and carefully paced at every stage of delivery.' },
    ar: { shortDescription: 'تنسيق خاص يتمحور حول Türkiye ويُصاغ وفق إيقاعك وأولوياتك وأسلوب رحلتك.', longDescription: 'يجمع Private Celebration Design احتياجات الاحتفال أو السفر العائلي أو التخطيط المؤسسي حول Türkiye ضمن إطار واحد أنيق ومنضبط. وتبقى العملية واضحة وهادئة ومضبوطة الإيقاع في كل مرحلة من مراحل التنفيذ.' },
  },
  'corporate-retreat-curation': {
    tr: { shortDescription: 'Türkiye odağında, detayları sizin ritminize göre şekillenen özel planlama deneyimi.', longDescription: 'Corporate Retreat Curation, Türkiye odağında şekillenen kutlama, aile seyahati ya da kurumsal planlama ihtiyaçlarını tek bir zarif çatı altında toplar. Süreç, programın her aşamasında kontrollü iletişim, görünür operasyon ve ölçülü bir teslim standardıyla ilerler.' },
    en: { shortDescription: 'A bespoke planning format shaped around Türkiye, refined to your pace, priorities and style of travel.', longDescription: 'Corporate Retreat Curation gathers celebration, family travel or corporate planning needs around Türkiye into one controlled and elegant framework. The process remains visible, discreet and carefully paced at every stage of delivery.' },
    ar: { shortDescription: 'تنسيق خاص يتمحور حول Türkiye ويُصاغ وفق إيقاعك وأولوياتك وأسلوب رحلتك.', longDescription: 'يجمع Corporate Retreat Curation احتياجات الاحتفال أو السفر العائلي أو التخطيط المؤسسي حول Türkiye ضمن إطار واحد أنيق ومنضبط. وتبقى العملية واضحة وهادئة ومضبوطة الإيقاع في كل مرحلة من مراحل التنفيذ.' },
  },
  'family-heritage-journey': {
    tr: { shortDescription: 'Türkiye odağında, detayları sizin ritminize göre şekillenen özel planlama deneyimi.', longDescription: 'Family Heritage Journey, Türkiye odağında şekillenen kutlama, aile seyahati ya da kurumsal planlama ihtiyaçlarını tek bir zarif çatı altında toplar. Süreç, programın her aşamasında kontrollü iletişim, görünür operasyon ve ölçülü bir teslim standardıyla ilerler.' },
    en: { shortDescription: 'A bespoke planning format shaped around Türkiye, refined to your pace, priorities and style of travel.', longDescription: 'Family Heritage Journey gathers celebration, family travel or corporate planning needs around Türkiye into one controlled and elegant framework. The process remains visible, discreet and carefully paced at every stage of delivery.' },
    ar: { shortDescription: 'تنسيق خاص يتمحور حول Türkiye ويُصاغ وفق إيقاعك وأولوياتك وأسلوب رحلتك.', longDescription: 'يجمع Family Heritage Journey احتياجات الاحتفال أو السفر العائلي أو التخطيط المؤسسي حول Türkiye ضمن إطار واحد أنيق ومنضبط. وتبقى العملية واضحة وهادئة ومضبوطة الإيقاع في كل مرحلة من مراحل التنفيذ.' },
  },
};
